### ISSUE TITLE
Where would you live if you could live anywhere?

### ISSUE THREAD

**Issue by sindresorhus** [cassiemc/ama#11]

**Comment by cassiemc** [comment]
Maybe New Mexico. There's something charming about the arts culture there, and it's a unique environment. I like the idea of building a house and carving little flourishes in every corner from adobe. 

But I like where I am too (small town Ontario, see issue #1). It's a good compromise in cultures and lifestyles for my husband (who is English but grew up in Luxembourg) and me (who grew up in Florida). Canada seems to match our values, we're both (fairly) equally separated from our families, and we still feel like there's a lot we can do here. We talk about retiring in England or Florida but a lot depends on where our families will be. 

At a certain point I find most places similar to some other place I've already been. The novelty of moving around has definitely worn off for me, and people have become much much more important.
