### ISSUE TITLE
What did you have for lunch?

### ISSUE THREAD

**Issue by sindresorhus** [cassiemc/ama#12]

**Comment by cassiemc** [comment]
On the day you asked this, I had a curried lentils, beans and rice I'd made earlier in the week mixed with salad and cheese. I try to make a big batch of something every week that I can mix with various things throughout the week for lunches. 

On the day I read this, I had two bites of my daughter's leftover peanut butter sandwich, some wild black raspberries we picked this morning and a slice of banana cake with peanut butter icing.
