### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [cassiemc/ama#14]

**Comment by cassiemc** [comment]
Yes, it's a big part of my job as Design Director at the foundation with my direct employees. I also am responsive if people email me thoughtful quesitons. Someone emailed this morning for advice and I wrote back a novel, pretty much immediately. For awhile I was participating in Office Hours, which I recommend: https://officehours.io/ 

It's hard for me to commit to regular in-person meetings at this stage in my life, working remotely with a small kid and another on the way, but I'll squeeze in Skype calls when I can if that's desired.
