### ISSUE TITLE
How are we doing with Women in tech?

### ISSUE THREAD

**Issue by wesbos** [cassiemc/ama#2]
Women&&Tech has been around for a while. How are we, the web industry as a whole, doing with diversity in tech?

Seems like every day I see amazing things like Ladies Learning Code and conferences that have well balanced speaker sets. Then I see things [like this](https://blog.jessfraz.com/post/this-industry-is-fucked/) that makes me really sad for our industry.

**Comment by cassiemc** [comment]
Oh man, I'm not qualified to answer this widely or with any kind of finality. So I will just answer personally. I've never been familiar with abhorrent abuse except what I read on the internet (nothing extreme has ever been sent my way, and I've not heard about anything like that from friends). By no means does it not exist, I just don't have experience with it. The things I've experienced are milder, and probably still impact my career. I like the idea of micro-politics embraced by [third wave feminists](https://en.wikipedia.org/wiki/Third-wave_feminism) – tweaks we can make to existing political systems to better support women and tear down the more subtle power structures that have been in place for hundreds of years.

This is simply anecdotal but from my perspective in the middle of the road, I agree we're doing better with gender-balance in speaker lineups at conferences and in education / reaching and supporting young girls. Judging panels, leadership and any group of people deemed as experts still seems to skew male from what I've seen. That's a shame – I think women manage and declare themselves experts differently from men, so I'd love to see some changes in the way different communication styles are valued and how performance is assessed. There are also some easy easy fixes to do in hiring; I'm sure many people do this already but Mozilla does not yet, which is to have blind applications where the name and gender are hidden from the reviewer.

Re. diversity, I think we have even farther to go than with women in learning to support, reach and empower other marginalized groups.

You see a lot of good things happen every day, but you also see a lot of bad. I wonder if the Internet will always be that way. It's really awesome to see so many people speaking up for under-privileged groups and trying every day to be better and do better.

**Comment by wesbos** [comment]
:clap: :clap: :clap:  Thank you :)

**Comment by rex** [comment]
@wesbos Thank you for asking this question and @cassiemc thank you for fielding it. You're a good sport, and your response was a great read.

I particularly like the idea of "blind applications" in which the name and gender of the applicant are hidden. Given that these pieces of information serve _absolutely zero_ purpose in evaluating the candidate's overall ability to perform the job I can't imagine this would be hard to adopt at least in principle. Fingers crossed that the industry embraces ideas like this.
