### ISSUE TITLE
How do you handle creative block? What gives you inspiration when you're feeling uninspired?

### ISSUE THREAD

**Issue by darrinhenein** [cassiemc/ama#4]

**Comment by cassiemc** [comment]
Taking a walk, taking a nap, talking to someone, reading, twitter, doodling, looking at books, looking at Dribbble or Awaaards or Pinterest or some nonsense like that. 

To be honest I'm rarely uninspired, my mind is always whizzing, sometimes off into stupid places but at least it is whizzing. Most of the time I have to force myself to stop being overinspired which grinds me to a halt much more than a creative block.

However, if you're talking about how I find inspiration when I _have_ to do something that I _don't want_ to do, like my taxes or designing an email template, I literally take things five minutes at a time. I force myself to get started (usually by scheduling a meeting that I need to be accountable for) then if I finish five minutes I reward myself with cookies or tea then do another five minutes. And after 20 minutes or so I'm kind of into it.
