### ISSUE TITLE
What are you looking for on the Webmaker project?

### ISSUE THREAD

**Issue by jenstrickland** [cassiemc/ama#6]
I'm extremely interested in an opening on your Webmaker project. What would make me your perfect candidate?

**Comment by cassiemc** [comment]
Hi @jenstrickland, I think you're referring to the open design position (which is for all of Mozilla Foundation, not just Webmaker). If so, I've written a bunch recently about the design hiring process on my blog. All the posts are logged here: http://www.cassiemcdaniel.com/blog/designers-get-hired/ Feel free to open another issue if that doesn't answer your question!
