### ISSUE TITLE
What was the thing that surprised you most about becoming a parent?

### ISSUE THREAD

**Issue by bwinton** [cassiemc/ama#7]

**Comment by cassiemc** [comment]
Lots of things have surprised me, but in terms of _most_, I guess it was how being a parent has altered my sense of time.

I thought I would be terrible at knowing how to feed, bathe, clothe, protect, encourage her... I didn't realize that I didn't need to know how to do everything at once, and that time would actually slow down as she and I learned how to do things together. Maybe a life lesson for getting your feet wet in situations that scare you, being patient with yourself, learning on the job and such.

Some days are soooooo long, they never seem to end, and then some days feel so quick that it seems all our time was spent on bodily functions. Either way you look back at these days and they are just snapshots of everything you've been through. It's that weird thing where the days are long and years are short, I know. I felt that before becoming a parent too but it is much more potent when you're watching a person grow up every day.

I guess my feeling of time is different in that it feels more relevant. I know I have to savor the time when she's little and she actually wants me to tickle her, and that makes me feel more present everyday in all that I do. The past matters less, the future matters more, and the present matters most.

Cheesy? Eh whatever, it's true!
