### ISSUE TITLE
What's your favourite word?

### ISSUE THREAD

**Issue by arthurvr** [cassiemc/ama#8]

**Comment by cassiemc** [comment]
Perhaps "banana". I thought it was hysterical when I was younger thinking of all the different ways you could pronounce it with long a's and short a's and accents on different parts.

My daughter has a book out from the library right now called _Bubble Trouble_ that is full of delicious words like bobble, quibble, grovel, grapple, gargle, drivel. Civil is kind of a nice word. Obviously I like words with interesting sounds. :)
